### ISSUE TITLE
What does "require('contacts/app/main')" do in the example app?

### ISSUE THREAD

**Issue by iagooar** [charlesjolley/node-ember#5]
I have been trying to implement my own scaffold app node + ember app based on the Contacts example.

The thing is I am using a different directory structure and with coffeescript, so I need to understand where this line comes from and what it means:

https://github.com/charlesjolley/node-ember/blob/master/examples/contacts/app/index.html#L11

``` javascript
<script>require('contacts/app/main')</script>
```

Where comes the "contacts" namespace from? Is contacts/app/main the main.js in the example app? If so, how would you link to it if it was a coffeescript file? If it is the same file, why is it linked in the convoy definition and then referenced in the index.html file?

Thanks in advance!

**Comment by pharcosyle** [comment]
Yup, the contacts "namespace" just comes from the directory structure (root folder of the project on the machine where your app is running). I use heroku so I had to to use 'app' because that's what a heroku dyno calls its root directory.

Not sure if a coffee file would work. In my project I have a main.js file with

```
require('coffee-script');
require('./lib/server');
```

and lib/server is a coffee file (as are all the other files in my project); requiring coffeescript from the code makes require() calls work for .coffee files directly

**Comment by charlesjolley** [comment]
yeah this is an annoying limitation of how node.js resolves paths. I've looked into solving this somehow but so far no luck. I have to name all my apps 'app' also..

**Comment by charlesjolley** [comment]
Closing this ticket since it was a question, not an issue.
